version: '3.7'

services:
  wireguard:
    # image: linuxserver/wireguard
    image: us-east1-docker.pkg.dev/sandbox-1-383001/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - SERVERURL=1.1.1.1 #optional
#      - SERVERURL=maliam.duckdns.org #optional
      - SERVERPORT=51820 #optional
      - PEERS=2 #optional
      - PEERDNS=auto #optional
#      - PEERDNS=192.168.4.15 #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
    volumes:
      - ./wireguard:/config
      - /lib/modules:/lib/modules
      - /usr/src:/usr/src
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    # dns:
    #   - 172.20.0.7
    restart: unless-stopped
    # networks:
    #   containers:
    #     ipv4_address: 172/20.0.16
